version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root    
    ports:
      - 8020:8080
      - 441:443
      - 50000:50000
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config

volumes:
  jenkins_home:
    driver: local
  jenkins_config:
    driver: local
         
